### ISSUE TITLE
Can I ask one question?

### ISSUE THREAD

**Issue by tim-hub** [gotojeffray/whv_detect#1]
I know the picture code now.

But do you know about that js on the website, it blocked the data fetching. I cannot get data. I think the verification code we can get some api to fix it, but do you know about the js to avoid the robots visiting?

**Comment by gotojeffray** [comment]
Sorry, I don't know about the js and they changed a lot on the web.

2017-06-18 16:27 GMT+12:00 Tim <notifications@github.com>:

**Comment by tim-hub** [comment]
thanks anyway
